# Write a program to accept marks of 6 students and display them in a sorted manner
marks=[]
s1=int(input("Enter mark of Student1:"))
marks.append(s1)
s2=int(input("Enter mark of Student2:"))
marks.append(s2)
s3=int(input("Enter mark of Student3:"))
marks.append(s3)
s4=int(input("Enter mark of Student4:"))
marks.append(s4)
s5=int(input("Enter mark of Student5:"))
marks.append(s5)
s6=int(input("Enter mark of Student6:"))
marks.append(s6)
print("Marks: ", marks)
marks.sort()
print("Sorted marks : ",marks)