# 2. Write a program to input eight numbers from the user and display all the unique
# numbers (once)
a = set()
a1=int(input("Enter a number: "))
a.add(a1)
a2=int(input("Enter a number: "))
a.add(a2)
a3=int(input("Enter a number: "))
a.add(a3)
a4=int(input("Enter a number: "))
a.add(a4)
a5=int(input("Enter a number: "))
a.add(a5)
a6=int(input("Enter a number: "))
a.add(a6)
a7=int(input("Enter a number: "))
a.add(a7)
a8=int(input("Enter a number: "))
a.add(a8)

print(a)